<a href="https://colab.research.google.com/github/ajinkyadhakne321-dot/PyTorch_practice/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. pytorch fundamentals
https://www.learnpytorch.io/00_pytorch_fundamentals/

### 1. Connect Colab to GitHub (if not already connected)

If you haven't already, you'll need to grant Colab access to your GitHub account. You can do this by navigating to `File` > `Save a copy to GitHub` (this option will also appear later).

When prompted, authorize Google Colab to access your GitHub repositories. You might need to generate a personal access token if you're working with private repositories or if prompted by GitHub for security reasons. Make sure the token has the `repo` scope (for full control over private repositories).

### 2. Save your Colab notebook to GitHub

Once connected, you can save your current notebook directly to a GitHub repository.

Go to `File` > `Save a copy to GitHub...`

- **Repository:** Select the desired GitHub repository.
- **Branch:** Choose the branch (e.g., `main` or `master`).
- **Path:** (Optional) Specify a folder within the repository.
- **Commit message:** Add a message describing your changes (e.g., 'Initial commit of PyTorch fundamentals notebook').

Then click `OK`.

### 3. Committing and Pushing Future Changes

After the initial save, you can directly commit and push changes from Colab:

Go to `File` > `Save a copy to GitHub...` again. Colab will detect that the notebook is already linked to a GitHub repository.

It will usually suggest committing changes directly to the linked repository and branch. Enter a descriptive commit message and click `OK`.

### Alternative: Use Git commands directly within Colab

You can also clone a repository and use standard Git commands within code cells. This gives you more control but requires familiarity with Git.

First, make sure to set up your Git credentials. You can use the following in a code cell (replace with your details):


In [ ]:
GIT_TOKEN = "YOUR_GITHUB_PERSONAL_ACCESS_TOKEN" # Store securely in Colab Secrets
USER_NAME = "Your GitHub Username"
USER_EMAIL = "your_email@example.com"

!git config --global user.email "{USER_EMAIL}"
!git config --global user.name "{USER_NAME}"

# Clone your repository (replace with your repo URL)
# For private repos, you might need to include your token:
# !git clone https://{GIT_TOKEN}@github.com/{USER_NAME}/your-repo-name.git
# For public repos or if token is set up globally:
# !git clone https://github.com/{USER_NAME}/your-repo-name.git

# Example: cloning a public repository
!git clone https://github.com/pytorch/examples.git

print("Repository cloned. You can now navigate into the directory and work with files.")

Once cloned, you can open, modify, and save files within that directory. To commit and push changes:


In [ ]:
# Navigate into your cloned repository directory
# %cd your-repo-name

# Example: navigate into 'examples' after cloning
%cd examples

!git add .
!git commit -m "My changes from Colab"
!git push origin main # Or your branch name (e.g., master)

Remember to store your GitHub Personal Access Token securely, preferably in Colab secrets, rather than directly in the notebook.

In [ ]:
print("hello i am exicited to learn pytorch")

hello i am exicited to learn pytorch


In [ ]:
!nvidia-smi #shows about gpu we are using


Wed Mar  4 19:43:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
print("hello i am exicited to learn pytorch")

hello i am exicited to learn pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


###tensor
main bilding block od dlor data

pytorch tensor are created using "torch.tensor"

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1] #indexing

tensor([ 9, 10])

In [ ]:
#tensor
tensor = torch.tensor([[[3,4,5],
                       [6,7,8],
                       [9,7,6]]])
tensor

tensor([[[3, 4, 5],
         [6, 7, 8],
         [9, 7, 6]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

2

In [ ]:
tensor[0]

tensor([[3, 4, 5],
        [6, 7, 8],
        [9, 7, 6]])

In [ ]:
#random tensors

###why random tensors?
random tensors are important beacuse the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5245, 0.6428, 0.4201, 0.8326],
        [0.5917, 0.3457, 0.5363, 0.3002],
        [0.9213, 0.9413, 0.9714, 0.5442]])

In [ ]:
random_tensor0 = torch.rand(10, 10, 10)
random_tensor0

tensor([[[8.6804e-01, 9.0998e-02, 1.6953e-01, 3.3633e-01, 3.7174e-01,
          8.6414e-01, 6.9909e-01, 3.5673e-01, 4.0040e-01, 6.6315e-01],
         [2.2366e-01, 9.5201e-01, 6.7177e-01, 2.8233e-02, 3.4199e-01,
          9.3584e-01, 8.6680e-01, 4.1259e-01, 4.7642e-01, 4.0533e-01],
         [9.7413e-01, 9.2495e-01, 4.2346e-01, 6.2286e-01, 3.3959e-01,
          9.9404e-01, 6.5613e-02, 7.9242e-01, 5.4552e-01, 3.8347e-01],
         [7.2966e-01, 1.6921e-01, 7.3555e-01, 2.3958e-02, 7.6187e-02,
          5.4424e-02, 2.4771e-01, 5.5556e-01, 9.9455e-01, 9.1137e-01],
         [5.2337e-01, 4.3293e-01, 9.5843e-02, 6.0735e-01, 3.9307e-01,
          1.6375e-01, 3.7026e-02, 1.9824e-01, 9.7741e-01, 2.5234e-01],
         [4.9211e-01, 7.2776e-01, 3.4033e-01, 9.6346e-01, 1.5756e-01,
          8.5072e-01, 3.6920e-01, 2.2054e-01, 6.2374e-01, 1.1445e-01],
         [4.4679e-01, 4.9613e-01, 9.6390e-02, 5.4408e-02, 8.8378e-01,
          9.3295e-01, 2.0778e-01, 6.9272e-01, 3.7225e-01, 6.5610e-01],
         [3.2

In [ ]:
random_tensor0.ndim

3

In [ ]:
#creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # size is dfault fun
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###tensor of zero and one

In [ ]:
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###creating range of tensors and tensor-like

In [ ]:
#use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor data types
**Note** tensors datatype is one of the three big errors with pytorch and deeplearning

1. tensors not right datatypes - to do get datatype from tensor
2. tensors not right shape - to do get shape from tensor
3. tensors not on the right device - to do get device from tensor



In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=int)
float_32_tensor.dtype
float_32_tensor

tensor([3, 6, 9])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor
some_tensor.shape, some_tensor.size()
#attribute          #function

(torch.Size([3, 4]), <function Tensor.size>)

In [ ]:
print("some_tensor")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"shape of tensor: {some_tensor.device}")


some_tensor
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
shape of tensor: cpu


###1. manipulating tensors(tensor operations)

2.tensor operation include

3.addition

4.sub

5.multi

6.divi

7.matrix


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# python inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])