<a href="https://colab.research.google.com/github/ajinkyadhakne321-dot/PyTorch_practice/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. pytorch fundamentals
https://www.learnpytorch.io/00_pytorch_fundamentals/

### 1. Connect Colab to GitHub (if not already connected)

If you haven't already, you'll need to grant Colab access to your GitHub account. You can do this by navigating to `File` > `Save a copy to GitHub` (this option will also appear later).

When prompted, authorize Google Colab to access your GitHub repositories. You might need to generate a personal access token if you're working with private repositories or if prompted by GitHub for security reasons. Make sure the token has the `repo` scope (for full control over private repositories).

### 2. Save your Colab notebook to GitHub

Once connected, you can save your current notebook directly to a GitHub repository.

Go to `File` > `Save a copy to GitHub...`

- **Repository:** Select the desired GitHub repository.
- **Branch:** Choose the branch (e.g., `main` or `master`).
- **Path:** (Optional) Specify a folder within the repository.
- **Commit message:** Add a message describing your changes (e.g., 'Initial commit of PyTorch fundamentals notebook').

Then click `OK`.

### 3. Committing and Pushing Future Changes

After the initial save, you can directly commit and push changes from Colab:

Go to `File` > `Save a copy to GitHub...` again. Colab will detect that the notebook is already linked to a GitHub repository.

It will usually suggest committing changes directly to the linked repository and branch. Enter a descriptive commit message and click `OK`.

### Alternative: Use Git commands directly within Colab

You can also clone a repository and use standard Git commands within code cells. This gives you more control but requires familiarity with Git.

First, make sure to set up your Git credentials. You can use the following in a code cell (replace with your details):


In [130]:
GIT_TOKEN = "YOUR_GITHUB_PERSONAL_ACCESS_TOKEN" # Store securely in Colab Secrets
USER_NAME = "Your GitHub Username"
USER_EMAIL = "your_email@example.com"

!git config --global user.email "{USER_EMAIL}"
!git config --global user.name "{USER_NAME}"

# Clone your repository (replace with your repo URL)
# For private repos, you might need to include your token:
# !git clone https://{GIT_TOKEN}@github.com/{USER_NAME}/your-repo-name.git
# For public repos or if token is set up globally:
# !git clone https://github.com/{USER_NAME}/your-repo-name.git

# Example: cloning a public repository
!git clone https://github.com/pytorch/examples.git

print("Repository cloned. You can now navigate into the directory and work with files.")

Cloning into 'examples'...
remote: Enumerating objects: 4900, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 4900 (delta 22), reused 19 (delta 19), pack-reused 4871 (from 2)
Receiving objects: 100% (4900/4900), 41.76 MiB | 18.08 MiB/s, done.
Resolving deltas: 100% (2413/2413), done.
Repository cloned. You can now navigate into the directory and work with files.


Once cloned, you can open, modify, and save files within that directory. To commit and push changes:


In [131]:
# Navigate into your cloned repository directory
# %cd your-repo-name

# Example: navigate into 'examples' after cloning
%cd examples

!git add .
!git commit -m "My changes from Colab"
!git push origin main # Or your branch name (e.g., master)

/content/examples/examples/examples
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address


Remember to store your GitHub Personal Access Token securely, preferably in Colab secrets, rather than directly in the notebook.

In [132]:
print("hello i am exicited to learn pytorch")

hello i am exicited to learn pytorch


In [133]:
!nvidia-smi #shows about gpu we are using


/bin/bash: line 1: nvidia-smi: command not found


In [134]:
print("hello i am exicited to learn pytorch")

hello i am exicited to learn pytorch


In [135]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


###tensor
main bilding block od dlor data

pytorch tensor are created using "torch.tensor"

In [136]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [137]:
scalar.ndim

0

In [138]:
scalar.item()

7

In [139]:
scalar.shape

torch.Size([])

In [140]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [141]:
vector.ndim

1

In [142]:
vector.size()

torch.Size([2])

In [143]:
#matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [144]:
matrix.ndim

2

In [145]:
matrix.shape

torch.Size([2, 2])

In [146]:
matrix[1] #indexing

tensor([ 9, 10])

In [147]:
#tensor
tensor = torch.tensor([[[3,4,5],
                       [6,7,8],
                       [9,7,6]]])
tensor

tensor([[[3, 4, 5],
         [6, 7, 8],
         [9, 7, 6]]])

In [148]:
tensor.shape

torch.Size([1, 3, 3])

In [149]:
tensor.ndim

3

In [150]:
tensor[0]

tensor([[3, 4, 5],
        [6, 7, 8],
        [9, 7, 6]])

In [151]:
#random tensors

###why random tensors?
random tensors are important beacuse the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

In [152]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4687, 0.2789, 0.8492, 0.4913],
        [0.0362, 0.7881, 0.9060, 0.1456],
        [0.5706, 0.0151, 0.8052, 0.4434]])

In [153]:
random_tensor0 = torch.rand(10, 10, 10)
random_tensor0

tensor([[[0.8723, 0.8125, 0.8047, 0.5549, 0.3273, 0.9462, 0.1258, 0.7911,
          0.9601, 0.4703],
         [0.2857, 0.5184, 0.1504, 0.5060, 0.2825, 0.9966, 0.8401, 0.7847,
          0.8252, 0.0531],
         [0.9202, 0.1094, 0.9139, 0.4267, 0.7120, 0.7375, 0.1726, 0.2633,
          0.1309, 0.0824],
         [0.4592, 0.2189, 0.2922, 0.3835, 0.3319, 0.1331, 0.0737, 0.2551,
          0.8583, 0.0625],
         [0.4731, 0.0361, 0.6010, 0.3828, 0.0181, 0.6905, 0.1378, 0.5758,
          0.8693, 0.1149],
         [0.8197, 0.9605, 0.9132, 0.2821, 0.8753, 0.9493, 0.6694, 0.8007,
          0.5589, 0.5025],
         [0.7787, 0.5955, 0.7356, 0.0208, 0.0041, 0.5408, 0.5008, 0.4708,
          0.9890, 0.5438],
         [0.3316, 0.5050, 0.3057, 0.0582, 0.5184, 0.8538, 0.2054, 0.6442,
          0.5551, 0.9707],
         [0.5397, 0.6857, 0.4567, 0.8811, 0.2732, 0.4835, 0.3346, 0.4293,
          0.4017, 0.9163],
         [0.9916, 0.2439, 0.7750, 0.0274, 0.6175, 0.5512, 0.3050, 0.3103,
          0.8210,

In [154]:
random_tensor0.ndim

3

In [155]:
#creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # size is dfault fun
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###tensor of zero and one

In [156]:
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [157]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [158]:
ones.dtype

torch.float32

###creating range of tensors and tensor-like

In [159]:
#use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
one_to_ten = torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [161]:
# creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor data types
**Note** tensors datatype is one of the three big errors with pytorch and deeplearning

1. tensors not right datatypes - to do get datatype from tensor
2. tensors not right shape - to do get shape from tensor
3. tensors not on the right device - to do get device from tensor



In [162]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [163]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=int)
float_32_tensor.dtype
float_32_tensor

tensor([3, 6, 9])

In [164]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [165]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [166]:
some_tensor = torch.rand(3, 4)
some_tensor
some_tensor.shape, some_tensor.size()
#attribute          #function

(torch.Size([3, 4]), torch.Size([3, 4]))

In [167]:
print("some_tensor")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"shape of tensor: {some_tensor.device}")


some_tensor
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
shape of tensor: cpu


###1. manipulating tensors(tensor operations)

2.tensor operation include

3.addition

4.sub

5.multi

6.divi

7.matrix

two rules to satisfy matrix multiplication

1. inner dimension must satisfied
* (3, 2) @ (3, 2) won't work
* (3, 2) @ (2, 2) will work
* (3, 3) @ (3, 2) will work

2. the resulting matrix has the shape of outer dimensions


In [168]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [169]:
tensor

tensor([1, 2, 3])

In [170]:
tensor - 10

tensor([-9, -8, -7])

In [171]:
tensor * 10

tensor([10, 20, 30])

In [172]:
# python inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [173]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###marix multiplication
two main ways to perform multiplication in dl an nn
1. element wise multiplication
2. matrix multiplication(dot product)

In [174]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [175]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [176]:
### one of the most common error in dl

In [177]:
torcho9 = torch.matmul(torch.rand(3, 3), torch.rand(3, 2))
torcho9

tensor([[0.5794, 0.4000],
        [0.7735, 0.8575],
        [0.6397, 0.8158]])

In [178]:
torcho9.ndim

2

### how to soleve the error with the multiplication of matrix

In [179]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_b = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
torch.mm(tensor_A, tensor_b) # torch.mm is the same as torch.matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# matrix multipication workes when tensor_b is trasposed

print(f"orignal shapes: tensor_A = {tensor_A.shape}, tensor_b = {tensor_b.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape}, tensor_b = {tensor_b.T.shape}")
print("multiplying:, {tensor_A.shape} @ {tensor_b.T.shape} <- inner dimension must match")
print("output:\n")
output = torch.matmul(tensor_A, tensor_b.T)
print(output)
print(f"\noutput shape: {output.shape}")

finding the mean,max,sum,etc(tensor aggregation)

In [180]:
#create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [181]:
#find the mean
torch.min(x), x.min()

(tensor(0), tensor(0))

In [182]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [183]:
#find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [184]:
#find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [185]:
###finding the positional min and max
print(x.argmax()) #max number at index

print(x.argmin()) #min number at index
print(x[9])





tensor(9)
tensor(0)
tensor(90)


###reshaping, stacking, squeezing and unsqueezing
*reshaping - reshapes an input tensor to a defined shape

*view - return a view of an input tensor of certain shape but keep the same memory as the orignal tensor

*stacking - combine multiple tensor on top of each other(vstack) or side by side (hstack)

*unsqueeze - add a one dimension to a target tensor

*permute - return a view of the input with dimension permuted in a certian way

In [186]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [187]:
#add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [188]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [189]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [191]:
#changing z changes x (beacuse a view of a tensor shares the same memory as the orignal input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [192]:
#stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [193]:
x_stacked = torch.stack([x, x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [194]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nsqueezed tensor: {x_squeezed}")
print(f"squeezed shape: {x_squeezed.shape}")

previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape: torch.Size([9, 1])

squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
squeezed shape: torch.Size([9])


In [198]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
print(f"unsqueezed tensor is: {x_squeezed.unsqueeze(dim = 0)}")
print(x_squeezed.unsqueeze(dim = 0).shape)

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])
unsqueezed tensor is: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [201]:
print(f"unsqueezed tensor is: {x_squeezed.unsqueeze(dim = 1)}")
print(x_squeezed.unsqueeze(dim = 1).shape)

unsqueezed tensor is: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [202]:
#torch.permute - rearranges the dimensions of a target tensor in specific order
x_original = torch.rand(size = (224, 224, 3)) #[height, width, colour_channels]
#permute the orignal tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 ->1, 1 -> 2, 2 -> 0
print(f"previous dim: {x_original.shape}")
print(f"new dim: {x_permuted.shape}")

previous dim: torch.Size([224, 224, 3])
new dim: torch.Size([3, 224, 224])
